name: Remove Snyk Gradle SCM Projects

on:
  workflow_dispatch

jobs:
  remove-gradle-snyk:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Run Script
      run: |
        ORG_ID=${{ secrets.SNYK_ORG_ID }}
        SNYK_TOKEN=${{ secrets.SNYK_TOKEN }}
        PROJECTS_TO_DELETE=$(curl --location "https://api.snyk.io/rest/orgs/$ORG_ID/projects?version=2024-04-29&types=gradle&origins=github&limit=100" \
          --header "Authorization: token $SNYK_TOKEN" | jq -r '.data[].id')
        
        for PROJECT_ID in $PROJECTS_TO_DELETE; do
            RES=$(curl --location --request DELETE "https://api.snyk.io/rest/orgs/$ORG_ID/projects/$PROJECT_ID?version=2024-04-29" \
                --header "Authorization: token $SNYK_TOKEN")
            echo $RES
        done
      
