name: Snyk with Gradle

on:
  push:
    branches: [ "main" ]

jobs:
  snyk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: get workspace
        run: |
          ls
          pwd
        shell: bash
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/gradle@master
        with:
          args: --all-sub-projects --remote-repo-url=${{ github.event.repository.name }}
          command: monitor
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      
